In [7]:
import numpy as np
import torch.optim as optim

NameError: name 'petri_net' is not defined

In [43]:
a=np.arange(0,24).reshape(2,3,4)
b=np.arange(0,2)
c=(None,slice(None))*3
a[c].shape,a.shape

((1, 2, 1, 3, 1, 4), (2, 3, 4))

In [295]:
import numpy as np

class Petri_net(object):
    def __init__(self,mat_pre,mat_post,m0):
        self.mat_pre=mat_pre
        self.mat_post=mat_post
        self.mat=self.mat_post-self.mat_pre
        self.m=m0

    def is_tansition(self):
        self.tran=(self.m[:,None]>=self.mat_pre).all(0).nonzero()[0]   
        return  np.where(self.tran.size,True,False)  

    def firing(self,T):
        self.m=self.m+self.mat[:,T]     


mat_pre = np.loadtxt("D:\\petri_learning\\c.pre.txt")
mat_post = np.loadtxt("D:\\petri_learning\\c.post.txt")
m0 = np.loadtxt("D:\\petri_learning\\m0.txt")
petri_net=Petri_net(mat_pre,mat_post,m0)  
print(petri_net.mat) 
print("初始标识：",petri_net.m)
for x in range(10):
    if petri_net.is_tansition():  #判断是否存在可激发变迁
        tran_enable=np.random.choice(petri_net.tran)  #随机选择一个可激发变迁
    else:
        print("\n无可激发变迁！")
        break
    petri_net.firing(tran_enable)    #激发变迁
    print("\n可激发变迁：",petri_net.tran+1)
    print("激发变迁：",tran_enable+1)
    print("当前标识：",petri_net.m)





[[-1.  0.  0.  1.]
 [ 1. -1.  0.  0.]
 [ 1.  0. -1.  0.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -1.]]
初始标识： [3. 0. 0. 0. 0.]

可激发变迁： [1]
激发变迁： 1
当前标识： [2. 1. 1. 0. 0.]

可激发变迁： [1 2 3]
激发变迁： 3
当前标识： [2. 1. 0. 0. 1.]

可激发变迁： [1 2]
激发变迁： 2
当前标识： [2. 0. 0. 1. 1.]

可激发变迁： [1 4]
激发变迁： 4
当前标识： [3. 0. 0. 0. 0.]

可激发变迁： [1]
激发变迁： 1
当前标识： [2. 1. 1. 0. 0.]

可激发变迁： [1 2 3]
激发变迁： 3
当前标识： [2. 1. 0. 0. 1.]

可激发变迁： [1 2]
激发变迁： 2
当前标识： [2. 0. 0. 1. 1.]

可激发变迁： [1 4]
激发变迁： 1
当前标识： [1. 1. 1. 1. 1.]

可激发变迁： [1 2 3 4]
激发变迁： 1
当前标识： [0. 2. 2. 1. 1.]

可激发变迁： [2 3 4]
激发变迁： 2
当前标识： [0. 1. 2. 2. 1.]


1

In [10]:

(petri_net.m[:,None]>=petri_net.mat_pre).all(0)

array([False, False, False, False, False, False])

array([2., 1., 1., 0., 0.])

In [1]:
import numpy as np

class Petri_net(object):
    def __init__(self,mat_pre,mat_post,m0):
        self.mat_pre=mat_pre
        self.mat_post=mat_post
        self.mat=self.mat_post-self.mat_pre
        self.m=m0

    def is_tansition(self):
        self.tran=(self.m[:,None]>=self.mat_pre).all(0).nonzero()[0]   
        return  np.where(self.tran.size,True,False)  

    def firing(self,T):
        self.m=self.m+self.mat[:,T] 

class Node():
    def __init__(self, name):
        self.name = name
        self.next = None

class Graph_E(object):
    def __init__(self, node=None):
        self.head = node
        self.edge = {node.name:[]}


    def append_head_node(self,head_node):
        self.edge.update({head_node:[]})

    def append_next_node(self,head_node, node_name):
        
        self.edge[head_node].append(node_name)

class Graph_W(object):
    def __init__(self, head=None,t=None,next=None):
        self.head = head
        self.next = next
        self.t=t


class Graph_V(object):
    def __init__(self,mat_pre,mat_post,m0):
        self.mat_pre=mat_pre
        self.mat_post=mat_post
        self.mat=self.mat_post-self.mat_pre
        self.m=m0
        self.Vnew={0:m0}
        self.V={0:m0}
        self.num=0
    
    def is_empty_Vnew(self):  ##判断Vnew是否为空
        return np.where(len(self.Vnew),True,False)

    def is_empty_Te(self):    ##判断Te是否为空
        return np.where(len(self.Te),True,False)

    def node_choose(self):    ##从Vnew选择新节点
        #temp=np.random.choice(list(self.Vnew.keys()))
        temp=list(self.Vnew.keys())[0]
        return temp

    def Te_choose(self):    ##从Te选择一个可激发变迁
        ##temp=np.random.choice(self.Te)
        temp=self.Te[0]
        return temp

    def Vnew_delete(self,num): ##从Vnew删除选择节点
        self.Vnew.pop(num)

    def T_delete(self,t):     ##并从Te中删除
        self.Te=[x for x in self.Te if x!=t]

    def is_tansition(self,M):   #获得新节点的可激发变迁 返回可激发变迁是否为空
        self.Te=(M[:,None]>=self.mat_pre).all(0).nonzero()[0]   
        return  np.where(self.Te.size,True,False)  

    def firing(self,T,M):       ##随机选择一变迁激发  
        self.m=M+self.mat[:,T]   
        return self.m
    
    def is_new_node(self,m_new):  ##判断新节点是否在V中出现过
        temp=np.array([list(item) for item in self.V.values()])
        return np.where((temp==m_new[:None]).all(1).nonzero()[0].size,False,True)

    def node_update(self):
        self.num+=1
        self.Vnew.update({self.num:self.m})
        self.V.update({self.num:self.m})


def get_node_num(Dict,m):
    return [k for k, v in Dict.items() if (v == m).all(0)][0]

mat_pre = np.loadtxt("D:\\petri_learning\\c.pre.txt")
mat_post = np.loadtxt("D:\\petri_learning\\c.post.txt")
m0 = np.loadtxt("D:\\petri_learning\\m0.txt")
    

graph_v=Graph_V(mat_pre,mat_post,m0)
node=Node(0)
graph_e=Graph_E(node)
graph_w=Graph_W()

while(graph_v.is_empty_Vnew()):
    new_node=graph_v.node_choose()       #步骤4  从任意Vnew中选取新节点m
    graph_v.is_tansition(graph_v.V[new_node]) #步骤5  获得m可激发变迁Te
    graph_v.Vnew_delete(new_node)        #       并删除Vnew
    graph_e.append_head_node(new_node)
    while(graph_v.is_empty_Te()):
        tran_enable=graph_v.Te_choose()      #步骤6  从Te中随机选择一个可激发变迁
        graph_v.T_delete(tran_enable)        #       并将该变迁从Te中删除
        graph_v.firing(tran_enable,graph_v.V[new_node])          #步骤7  激发变迁  得到m'
        if graph_v.is_new_node(graph_v.m):        #步骤8  判断m'是不是新出现节点
            graph_v.node_update()            #       是  则更新V_new  V  W E

        print(new_node,tran_enable,get_node_num(graph_v.V,graph_v.m))
        graph_e.append_next_node(new_node,get_node_num(graph_v.V,graph_v.m))
    

graph_e.edge,graph_v.V



0 0 1
1 0 2
1 1 3
1 2 4
2 0 5
2 1 6
2 2 7
3 0 6
3 2 8
4 0 7
4 1 8
5 1 9
5 2 10
6 0 9
6 1 11
6 2 12
7 0 10
7 1 12
7 2 13
8 0 12
8 3 0
9 1 14
9 2 15
10 1 15
10 2 16
11 0 14
11 2 17
12 0 15
12 1 17
12 2 18
12 3 1
13 0 16
13 1 18
14 1 19
14 2 20
15 1 20
15 2 21
15 3 2
16 1 21
16 2 22
17 0 20
17 2 23
17 3 3
18 0 21
18 1 23
18 3 4
19 2 24
20 1 24
20 2 25
20 3 6
21 1 25
21 2 26
21 3 7
22 1 26
23 0 25
23 3 8
24 2 27
24 3 11
25 1 27
25 2 28
25 3 12
26 1 28
26 3 13
27 2 29
27 3 17
28 1 29
28 3 18
29 3 23


({0: [1],
  1: [2, 3, 4],
  2: [5, 6, 7],
  3: [6, 8],
  4: [7, 8],
  5: [9, 10],
  6: [9, 11, 12],
  7: [10, 12, 13],
  8: [12, 0],
  9: [14, 15],
  10: [15, 16],
  11: [14, 17],
  12: [15, 17, 18, 1],
  13: [16, 18],
  14: [19, 20],
  15: [20, 21, 2],
  16: [21, 22],
  17: [20, 23, 3],
  18: [21, 23, 4],
  19: [24],
  20: [24, 25, 6],
  21: [25, 26, 7],
  22: [26],
  23: [25, 8],
  24: [27, 11],
  25: [27, 28, 12],
  26: [28, 13],
  27: [29, 17],
  28: [29, 18],
  29: [23]},
 {0: array([3., 0., 0., 0., 0.]),
  1: array([2., 1., 1., 0., 0.]),
  2: array([1., 2., 2., 0., 0.]),
  3: array([2., 0., 1., 1., 0.]),
  4: array([2., 1., 0., 0., 1.]),
  5: array([0., 3., 3., 0., 0.]),
  6: array([1., 1., 2., 1., 0.]),
  7: array([1., 2., 1., 0., 1.]),
  8: array([2., 0., 0., 1., 1.]),
  9: array([0., 2., 3., 1., 0.]),
  10: array([0., 3., 2., 0., 1.]),
  11: array([1., 0., 2., 2., 0.]),
  12: array([1., 1., 1., 1., 1.]),
  13: array([1., 2., 0., 0., 2.]),
  14: array([0., 1., 3., 2., 0.]),
  1

AttributeError: 'list' object has no attribute 'push'

In [25]:


[k for k, v in graph_v.V.items() if (v == graph_v.m).all(0)][0]

30

In [20]:
graph_v.m

array([0., 0., 0., 0., 0., 2., 1.])

In [607]:
graph_v.V.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
modified_array = np.delete(a,(a==b).all(1).nonzero()[0],0)
modified_array

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np.where(a==b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [79]:
(a==b).all(1).nonzero()[0].size

0